CREATE TABLE employees
(
	empid INTEGER NOT NULL PRIMARY KEY,
	name CHARACTER VARYING,
	age INTEGER
);

CREATE TABLE students
(
	rollno INTEGER NOT NULL PRIMARY KEY,
	name CHARACTER VARYING,
	marks INTEGER
);
